
default:
#	./tikz2png.sh completeFSA completeFSA
#	./tikz2png.sh collapsedFSA collapsedFSA
#	./tikz2png.sh teaserSearch teaserSearch
#	./tikz2png.sh teaserManyPremises teaserManyPremises
#	./tikz2png.sh teaserBlindInferenceNaturalOrderBlind teaserBlindInferenceNaturalOrderBlind
#	./tikz2png.sh teaserBlindInferenceNaturalOrder teaserBlindInferenceNaturalOrder
#	./tikz2png.sh teaserBlindInference teaserBlindInference
#	./tikz2png.sh teaserInference teaserInference
#	./tikz2png.sh teaserFullDerivation teaserFullDerivation
#	./tikz2png.sh equivalentVenn equivalentVenn
#	./tikz2png.sh forwardVenn forwardVenn
#	./tikz2png.sh reverseVenn reverseVenn
#	./tikz2png.sh negateVenn negateVenn
#	./tikz2png.sh alternateVenn alternateVenn
#	./tikz2png.sh coverVenn coverVenn
#	./tikz2png.sh lattice lattice
#	./tikz2png.sh polarityOne polarity1
#	./tikz2png.sh polarityTwo polarity2
#	./tikz2png.sh polarityThree polarity3
#	./tikz2png.sh polarityFour polarity4
#	./tikz2png.sh polarityFive polarity5
#	./tikz2png.sh polaritySix polarity6
#	./tikz2png.sh exampleStepOne search1
#	./tikz2png.sh exampleStepTwo search2
#	./tikz2png.sh exampleStepThree search3
#	./tikz2png.sh exampleStepFour search4
#	./tikz2png.sh exampleStepFive search5
#	./tikz2png.sh exampleStepSix search6
#	./tikz2png.sh conceptnetResults conceptnetResults
#	./tikz2png.sh treeBlank treeBlank
#	./tikz2png.sh treeEdge treeEdge
#	./tikz2png.sh treeSubj treeSubj
#	./tikz2png.sh treeObj treeObj
#	./tikz2png.sh treeParent treeParent
#	./tikz2png.sh treeYield treeYield
#	./tikz2png.sh treeYieldSubj treeYieldSubj
#	./tikz2png.sh treeYieldObj treeYieldObj
#	./tikz2png.sh treeYieldRoot treeYieldRoot
	./tikz2png.sh openieKBPBase openieKBPBase
	./tikz2png.sh openieKBPFull openieKBPFull
#	bash exampleInference.sh



clean:
	rm -f *.aux *.log *.pdf *.png
